FROM golang:1.22-alpine

WORKDIR /producer

# Copy go.mod and go.sum files first to leverage Docker cache
# COPY go.mod go.sum ./

COPY ./Producer .

# Download dependencies
RUN go mod download

# RUN go build -o producerbinary main.go

# # Ensure the binary has executable permissions
# RUN chmod +x /producer/producerbinary

# Set the command to run the binary
CMD ["sh", "-c", "sleep infinity"]