FROM golang:1.22-alpine

WORKDIR /consumer

# Copy go.mod and go.sum files first to leverage Docker cache
# COPY go.mod go.sum ./

COPY ./Consumer .

# Download dependencies
RUN go mod download

RUN go build -o consumerbinary main.go

# # Ensure the binary has executable permissions
RUN chmod +x /consumer/consumerbinary

# Set the command to run the binary
# CMD ["sh", "-c", "sleep infinity"]
CMD ["./consumerbinary"]
