FROM bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8

# Run chmod 777 /
USER root
RUN hdfs dfs -mkdir -p /user/spark/kafka-data
#RUN hdfs dfs -chown -R spark:spark /user/spark
RUN hdfs dfs -chmod -R 777 /user/spark/kafka-data

# Switch back to hadoop user
#USER hadoop

