version: '3'
services:
  producer:
    container_name: producer
    build:
      context: .
      dockerfile: Dockerfile.producer
        # command: ["sh", "-c", "sleep infinity"]
    command: ["./producerbinary"]
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka_network

  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile.consumer  # Use the Dockerfile for the consumer
    command: ["./consumerbinary"]     
    depends_on:
      - kafka1 
      - kafka2
    networks:
      - kafka_network
    restart: always

  pytorch:
    container_name: pytorch
    build:
      context: .
      dockerfile: Dockerfile.pytorch  # Define your Dockerfile for PyTorch service
        #command: ["/bin/sh", "-c", "sleep infinity"]
        #command: ["python3", "llm.py"]
    command: ["./startup.sh"]
    depends_on:
      - kafka1
      - kafka2
    networks:
      - kafka_network
    restart: always

  kafka1:
    image: wurstmeister/kafka:latest
    container_name: kafka1
    ports:
      - "9094:9093"  # External port for kafka1
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9093,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1  # Unique broker ID for kafka1
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  kafka2:
    image: wurstmeister/kafka:latest
    container_name: kafka2
    ports:
      - "9095:9093"  # Different external port for kafka2
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka2:9093,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2  # Unique broker ID for kafka2
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge

